# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'asp3d_layout.ui'
#
# Created: Mon Aug 29 10:26:23 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1280, 1024)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(250000, 350000))
        MainWindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../asp3d_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.seisarray_active = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seisarray_active.sizePolicy().hasHeightForWidth())
        self.seisarray_active.setSizePolicy(sizePolicy)
        self.seisarray_active.setMaximumSize(QtCore.QSize(20, 20))
        self.seisarray_active.setMidLineWidth(0)
        self.seisarray_active.setText("")
        self.seisarray_active.setObjectName("seisarray_active")
        self.horizontalLayout_2.addWidget(self.seisarray_active)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.seisarray_on_survey_active = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seisarray_on_survey_active.sizePolicy().hasHeightForWidth())
        self.seisarray_on_survey_active.setSizePolicy(sizePolicy)
        self.seisarray_on_survey_active.setMaximumSize(QtCore.QSize(20, 20))
        self.seisarray_on_survey_active.setMidLineWidth(0)
        self.seisarray_on_survey_active.setText("")
        self.seisarray_on_survey_active.setObjectName("seisarray_on_survey_active")
        self.horizontalLayout_2.addWidget(self.seisarray_on_survey_active)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textBox_seisarray = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBox_seisarray.sizePolicy().hasHeightForWidth())
        self.textBox_seisarray.setSizePolicy(sizePolicy)
        self.textBox_seisarray.setObjectName("textBox_seisarray")
        self.verticalLayout.addWidget(self.textBox_seisarray)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setMinimumSize(QtCore.QSize(0, 5))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.survey_active = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.survey_active.sizePolicy().hasHeightForWidth())
        self.survey_active.setSizePolicy(sizePolicy)
        self.survey_active.setMaximumSize(QtCore.QSize(20, 20))
        self.survey_active.setMidLineWidth(0)
        self.survey_active.setText("")
        self.survey_active.setObjectName("survey_active")
        self.horizontalLayout.addWidget(self.survey_active)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.picked_active = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picked_active.sizePolicy().hasHeightForWidth())
        self.picked_active.setSizePolicy(sizePolicy)
        self.picked_active.setMaximumSize(QtCore.QSize(20, 20))
        self.picked_active.setMidLineWidth(0)
        self.picked_active.setText("")
        self.picked_active.setObjectName("picked_active")
        self.horizontalLayout.addWidget(self.picked_active)
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.textBox_survey = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBox_survey.sizePolicy().hasHeightForWidth())
        self.textBox_survey.setSizePolicy(sizePolicy)
        self.textBox_survey.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textBox_survey.setObjectName("textBox_survey")
        self.verticalLayout_2.addWidget(self.textBox_survey)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout_5)
        self.verticalLayout_right = QtGui.QVBoxLayout()
        self.verticalLayout_right.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_right.setObjectName("verticalLayout_right")
        self.horizontalLayout_tr = QtGui.QHBoxLayout()
        self.horizontalLayout_tr.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_tr.setObjectName("horizontalLayout_tr")
        self.verticalLayout_tr1 = QtGui.QVBoxLayout()
        self.verticalLayout_tr1.setObjectName("verticalLayout_tr1")
        self.horizontalLayout_tr.addLayout(self.verticalLayout_tr1)
        self.verticalLayout_right.addLayout(self.horizontalLayout_tr)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_right.addWidget(self.line_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.comboBox_stats = QtGui.QComboBox(self.centralwidget)
        self.comboBox_stats.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_stats.sizePolicy().hasHeightForWidth())
        self.comboBox_stats.setSizePolicy(sizePolicy)
        self.comboBox_stats.setMinimumSize(QtCore.QSize(450, 0))
        self.comboBox_stats.setObjectName("comboBox_stats")
        self.verticalLayout_6.addWidget(self.comboBox_stats)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_3.addWidget(self.line_5)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.shot_left = QtGui.QPushButton(self.centralwidget)
        self.shot_left.setMaximumSize(QtCore.QSize(25, 16777215))
        self.shot_left.setObjectName("shot_left")
        self.horizontalLayout_4.addWidget(self.shot_left)
        self.comboBox_shots = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_shots.sizePolicy().hasHeightForWidth())
        self.comboBox_shots.setSizePolicy(sizePolicy)
        self.comboBox_shots.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox_shots.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_shots.setObjectName("comboBox_shots")
        self.horizontalLayout_4.addWidget(self.comboBox_shots)
        self.shot_right = QtGui.QPushButton(self.centralwidget)
        self.shot_right.setMaximumSize(QtCore.QSize(25, 16777215))
        self.shot_right.setObjectName("shot_right")
        self.horizontalLayout_4.addWidget(self.shot_right)
        self.plot_shot = QtGui.QPushButton(self.centralwidget)
        self.plot_shot.setMaximumSize(QtCore.QSize(80, 16777215))
        self.plot_shot.setObjectName("plot_shot")
        self.horizontalLayout_4.addWidget(self.plot_shot)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_right.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_br = QtGui.QHBoxLayout()
        self.horizontalLayout_br.setObjectName("horizontalLayout_br")
        self.verticalLayout_br1 = QtGui.QVBoxLayout()
        self.verticalLayout_br1.setObjectName("verticalLayout_br1")
        self.horizontalLayout_br.addLayout(self.verticalLayout_br1)
        self.verticalLayout_br2 = QtGui.QVBoxLayout()
        self.verticalLayout_br2.setObjectName("verticalLayout_br2")
        self.horizontalLayout_br.addLayout(self.verticalLayout_br2)
        self.verticalLayout_right.addLayout(self.horizontalLayout_br)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.verticalLayout_right)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSeismic_Array = QtGui.QMenu(self.menubar)
        self.menuSeismic_Array.setObjectName("menuSeismic_Array")
        self.menuSurvey = QtGui.QMenu(self.menubar)
        self.menuSurvey.setObjectName("menuSurvey")
        self.menuPicking = QtGui.QMenu(self.menubar)
        self.menuPicking.setObjectName("menuPicking")
        self.menuSimulation = QtGui.QMenu(self.menubar)
        self.menuSimulation.setObjectName("menuSimulation")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Seismic_Array = QtGui.QAction(MainWindow)
        self.actionLoad_Seismic_Array.setCheckable(False)
        self.actionLoad_Seismic_Array.setObjectName("actionLoad_Seismic_Array")
        self.actionSave_Seismic_Array = QtGui.QAction(MainWindow)
        self.actionSave_Seismic_Array.setObjectName("actionSave_Seismic_Array")
        self.actionLoad_Survey = QtGui.QAction(MainWindow)
        self.actionLoad_Survey.setObjectName("actionLoad_Survey")
        self.actionSave_Survey = QtGui.QAction(MainWindow)
        self.actionSave_Survey.setObjectName("actionSave_Survey")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionGenerate_new_Seismic_Array = QtGui.QAction(MainWindow)
        self.actionGenerate_new_Seismic_Array.setObjectName("actionGenerate_new_Seismic_Array")
        self.actionInterpolate_Receivers = QtGui.QAction(MainWindow)
        self.actionInterpolate_Receivers.setObjectName("actionInterpolate_Receivers")
        self.actionConnect_to_Survey = QtGui.QAction(MainWindow)
        self.actionConnect_to_Survey.setObjectName("actionConnect_to_Survey")
        self.actionGenerate_new_Survey = QtGui.QAction(MainWindow)
        self.actionGenerate_new_Survey.setObjectName("actionGenerate_new_Survey")
        self.actionAutomatic_Picking = QtGui.QAction(MainWindow)
        self.actionAutomatic_Picking.setObjectName("actionAutomatic_Picking")
        self.actionPostprocessing = QtGui.QAction(MainWindow)
        self.actionPostprocessing.setObjectName("actionPostprocessing")
        self.actionStart_FMTOMO_Simulation = QtGui.QAction(MainWindow)
        self.actionStart_FMTOMO_Simulation.setObjectName("actionStart_FMTOMO_Simulation")
        self.actionVTK_Visualization = QtGui.QAction(MainWindow)
        self.actionVTK_Visualization.setObjectName("actionVTK_Visualization")
        self.actionSeismic_Array = QtGui.QAction(MainWindow)
        self.actionSeismic_Array.setEnabled(False)
        self.actionSeismic_Array.setObjectName("actionSeismic_Array")
        self.actionFullscreen = QtGui.QAction(MainWindow)
        self.actionFullscreen.setCheckable(True)
        self.actionFullscreen.setObjectName("actionFullscreen")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSeismic_Array.addAction(self.actionGenerate_new_Seismic_Array)
        self.menuSeismic_Array.addAction(self.actionLoad_Seismic_Array)
        self.menuSeismic_Array.addAction(self.actionSave_Seismic_Array)
        self.menuSeismic_Array.addSeparator()
        self.menuSeismic_Array.addAction(self.actionInterpolate_Receivers)
        self.menuSeismic_Array.addAction(self.actionConnect_to_Survey)
        self.menuSurvey.addAction(self.actionGenerate_new_Survey)
        self.menuSurvey.addAction(self.actionLoad_Survey)
        self.menuSurvey.addAction(self.actionSave_Survey)
        self.menuPicking.addAction(self.actionAutomatic_Picking)
        self.menuPicking.addAction(self.actionPostprocessing)
        self.menuSimulation.addAction(self.actionStart_FMTOMO_Simulation)
        self.menuTools.addAction(self.actionVTK_Visualization)
        self.menuView.addAction(self.actionFullscreen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSurvey.menuAction())
        self.menubar.addAction(self.menuSeismic_Array.menuAction())
        self.menubar.addAction(self.menuPicking.menuAction())
        self.menubar.addAction(self.menuSimulation.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ActiveSeismoPick 3D", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Seismic Array", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "active", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "connected to Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "active", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "picked", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Plot Receiver and Shots of the Array colored by:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Plot a single Shot:", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_left.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_right.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_shot.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSeismic_Array.setTitle(QtGui.QApplication.translate("MainWindow", "Seismic Array", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSurvey.setTitle(QtGui.QApplication.translate("MainWindow", "Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPicking.setTitle(QtGui.QApplication.translate("MainWindow", "Picking", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSimulation.setTitle(QtGui.QApplication.translate("MainWindow", "Inversion", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Seismic_Array.setText(QtGui.QApplication.translate("MainWindow", "Load Seismic Array", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Seismic_Array.setText(QtGui.QApplication.translate("MainWindow", "Save Seismic Array", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Survey.setText(QtGui.QApplication.translate("MainWindow", "Load Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Survey.setText(QtGui.QApplication.translate("MainWindow", "Save Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_new_Seismic_Array.setText(QtGui.QApplication.translate("MainWindow", "Generate new Seismic Array", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInterpolate_Receivers.setText(QtGui.QApplication.translate("MainWindow", "Interpolate Receivers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect_to_Survey.setText(QtGui.QApplication.translate("MainWindow", "Connect to Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_new_Survey.setText(QtGui.QApplication.translate("MainWindow", "Generate new Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutomatic_Picking.setText(QtGui.QApplication.translate("MainWindow", "Automatic Picking", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPostprocessing.setText(QtGui.QApplication.translate("MainWindow", "Postprocessing", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_FMTOMO_Simulation.setText(QtGui.QApplication.translate("MainWindow", "Start FMTOMO Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVTK_Visualization.setText(QtGui.QApplication.translate("MainWindow", "VTK Visualization", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSeismic_Array.setText(QtGui.QApplication.translate("MainWindow", "Seismic Array", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFullscreen.setText(QtGui.QApplication.translate("MainWindow", "Fullscreen", None, QtGui.QApplication.UnicodeUTF8))

