# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fmtomo_parameters_layout.ui'
#
# Created: Thu Aug  4 12:07:57 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_fmtomo_parameters(object):
    def setupUi(self, fmtomo_parameters):
        fmtomo_parameters.setObjectName("fmtomo_parameters")
        fmtomo_parameters.resize(400, 440)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(fmtomo_parameters.sizePolicy().hasHeightForWidth())
        fmtomo_parameters.setSizePolicy(sizePolicy)
        fmtomo_parameters.setMinimumSize(QtCore.QSize(400, 440))
        fmtomo_parameters.setMaximumSize(QtCore.QSize(320000, 520000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../asp3d_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        fmtomo_parameters.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(fmtomo_parameters)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_17 = QtGui.QLabel(fmtomo_parameters)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.fmtomo_dir = QtGui.QLineEdit(fmtomo_parameters)
        self.fmtomo_dir.setObjectName("fmtomo_dir")
        self.horizontalLayout_4.addWidget(self.fmtomo_dir)
        self.browse_tomodir = QtGui.QPushButton(fmtomo_parameters)
        self.browse_tomodir.setObjectName("browse_tomodir")
        self.horizontalLayout_4.addWidget(self.browse_tomodir)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_5 = QtGui.QFrame(fmtomo_parameters)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtGui.QLabel(fmtomo_parameters)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.nproc = QtGui.QSpinBox(fmtomo_parameters)
        self.nproc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nproc.setMinimum(1)
        self.nproc.setMaximum(10000)
        self.nproc.setObjectName("nproc")
        self.horizontalLayout_2.addWidget(self.nproc)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.nIter = QtGui.QSpinBox(fmtomo_parameters)
        self.nIter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nIter.setProperty("value", 1)
        self.nIter.setObjectName("nIter")
        self.gridLayout_3.addWidget(self.nIter, 0, 1, 1, 1)
        self.label = QtGui.QLabel(fmtomo_parameters)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.line_4 = QtGui.QFrame(fmtomo_parameters)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.label_18 = QtGui.QLabel(fmtomo_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtGui.QLabel(fmtomo_parameters)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.bbot = QtGui.QLineEdit(fmtomo_parameters)
        self.bbot.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bbot.setObjectName("bbot")
        self.gridLayout_2.addWidget(self.bbot, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(fmtomo_parameters)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(fmtomo_parameters)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.btop = QtGui.QLineEdit(fmtomo_parameters)
        self.btop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.btop.setObjectName("btop")
        self.gridLayout_2.addWidget(self.btop, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(fmtomo_parameters)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtGui.QLabel(fmtomo_parameters)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.cushion = QtGui.QSpinBox(fmtomo_parameters)
        self.cushion.setMinimum(2)
        self.cushion.setMaximum(100)
        self.cushion.setProperty("value", 10)
        self.cushion.setObjectName("cushion")
        self.horizontalLayout.addWidget(self.cushion)
        self.label_12 = QtGui.QLabel(fmtomo_parameters)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line = QtGui.QFrame(fmtomo_parameters)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtGui.QLabel(fmtomo_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(fmtomo_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(fmtomo_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(fmtomo_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 3, 1, 1)
        self.label_9 = QtGui.QLabel(fmtomo_parameters)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.pgrid_x = QtGui.QSpinBox(fmtomo_parameters)
        self.pgrid_x.setMinimum(2)
        self.pgrid_x.setMaximum(10000)
        self.pgrid_x.setProperty("value", 100)
        self.pgrid_x.setObjectName("pgrid_x")
        self.gridLayout.addWidget(self.pgrid_x, 1, 1, 1, 1)
        self.pgrid_y = QtGui.QSpinBox(fmtomo_parameters)
        self.pgrid_y.setMinimum(2)
        self.pgrid_y.setMaximum(10000)
        self.pgrid_y.setProperty("value", 100)
        self.pgrid_y.setObjectName("pgrid_y")
        self.gridLayout.addWidget(self.pgrid_y, 1, 2, 1, 1)
        self.pgrid_z = QtGui.QSpinBox(fmtomo_parameters)
        self.pgrid_z.setMinimum(2)
        self.pgrid_z.setMaximum(10000)
        self.pgrid_z.setProperty("value", 120)
        self.pgrid_z.setObjectName("pgrid_z")
        self.gridLayout.addWidget(self.pgrid_z, 1, 3, 1, 1)
        self.label_8 = QtGui.QLabel(fmtomo_parameters)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.invgrid_x = QtGui.QSpinBox(fmtomo_parameters)
        self.invgrid_x.setMinimum(2)
        self.invgrid_x.setMaximum(10000)
        self.invgrid_x.setProperty("value", 60)
        self.invgrid_x.setObjectName("invgrid_x")
        self.gridLayout.addWidget(self.invgrid_x, 2, 1, 1, 1)
        self.invgrid_y = QtGui.QSpinBox(fmtomo_parameters)
        self.invgrid_y.setMinimum(2)
        self.invgrid_y.setMaximum(10000)
        self.invgrid_y.setProperty("value", 60)
        self.invgrid_y.setObjectName("invgrid_y")
        self.gridLayout.addWidget(self.invgrid_y, 2, 2, 1, 1)
        self.invgrid_z = QtGui.QSpinBox(fmtomo_parameters)
        self.invgrid_z.setMinimum(2)
        self.invgrid_z.setMaximum(10000)
        self.invgrid_z.setProperty("value", 80)
        self.invgrid_z.setObjectName("invgrid_z")
        self.gridLayout.addWidget(self.invgrid_z, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line_2 = QtGui.QFrame(fmtomo_parameters)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.line_3 = QtGui.QFrame(fmtomo_parameters)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_15 = QtGui.QLabel(fmtomo_parameters)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.customgrid = QtGui.QLineEdit(fmtomo_parameters)
        self.customgrid.setObjectName("customgrid")
        self.gridLayout_4.addWidget(self.customgrid, 0, 1, 1, 1)
        self.browse_customgrid = QtGui.QPushButton(fmtomo_parameters)
        self.browse_customgrid.setObjectName("browse_customgrid")
        self.gridLayout_4.addWidget(self.browse_customgrid, 0, 2, 1, 1)
        self.label_16 = QtGui.QLabel(fmtomo_parameters)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 1, 0, 1, 1)
        self.simuldir = QtGui.QLineEdit(fmtomo_parameters)
        self.simuldir.setObjectName("simuldir")
        self.gridLayout_4.addWidget(self.simuldir, 1, 1, 1, 1)
        self.browse_simuldir = QtGui.QPushButton(fmtomo_parameters)
        self.browse_simuldir.setObjectName("browse_simuldir")
        self.gridLayout_4.addWidget(self.browse_simuldir, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.buttonBox = QtGui.QDialogButtonBox(fmtomo_parameters)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(fmtomo_parameters)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), fmtomo_parameters.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), fmtomo_parameters.reject)
        QtCore.QMetaObject.connectSlotsByName(fmtomo_parameters)

    def retranslateUi(self, fmtomo_parameters):
        fmtomo_parameters.setWindowTitle(QtGui.QApplication.translate("fmtomo_parameters", "Choose FMTOMO parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setToolTip(QtGui.QApplication.translate("fmtomo_parameters", "Directory containing a clean FMTOMO installation.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("fmtomo_parameters", "FMTOMO\n"
"installation [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.browse_tomodir.setText(QtGui.QApplication.translate("fmtomo_parameters", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setToolTip(QtGui.QApplication.translate("fmtomo_parameters", "Number of processes spawned for parallel forward simulation.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("fmtomo_parameters", "Number of processes [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setToolTip(QtGui.QApplication.translate("fmtomo_parameters", "Number of inversion iterations.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("fmtomo_parameters", "Iterations [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("fmtomo_parameters", "Grid definitions from seismic Array:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setToolTip(QtGui.QApplication.translate("fmtomo_parameters", "Bottom boundary of the model.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("fmtomo_parameters", "Bottom boundary [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.bbot.setText(QtGui.QApplication.translate("fmtomo_parameters", "-50", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("fmtomo_parameters", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setToolTip(QtGui.QApplication.translate("fmtomo_parameters", "Top boundary of the model (must be greater than highest source or receiver position).\n"
"Too low values will cause error.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("fmtomo_parameters", "Top boundary [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.btop.setText(QtGui.QApplication.translate("fmtomo_parameters", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("fmtomo_parameters", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setToolTip(QtGui.QApplication.translate("fmtomo_parameters", "Extension of the model around the maximum values of the receiver grid (X and Y).\n"
"Too low values will cause error.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("fmtomo_parameters", "Cushion factor [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("fmtomo_parameters", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("fmtomo_parameters", "Number of Points", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("fmtomo_parameters", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("fmtomo_parameters", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("fmtomo_parameters", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setToolTip(QtGui.QApplication.translate("fmtomo_parameters", "Number of inversion grid (velocity grid) points in X, Y, Z.\n"
"Must be lower than for propagation grid.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("fmtomo_parameters", "Inversion Grid [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setToolTip(QtGui.QApplication.translate("fmtomo_parameters", "Number of points for forward simulation in X, Y, Z.\n"
"Must be higher than number of inversion grid points.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("fmtomo_parameters", "Propagation Grid [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setToolTip(QtGui.QApplication.translate("fmtomo_parameters", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Specifiy simple input velocity file from which linear gradients will be evaluated.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">For example:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">First gradient: Surface velocity: 0.5 km/s rising to 1.0 km/s at a depth of 5 m below the surface.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Second gradient: Continuous change to another gradient from 1.0 km/s to 4.0 km/s at 60 m depth below the surface.</p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0        0.5</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-5       1.0</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-5       1.0</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-60     4.0</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("fmtomo_parameters", "Custom velocity\n"
"grid (earthmodel) [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.browse_customgrid.setText(QtGui.QApplication.translate("fmtomo_parameters", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setToolTip(QtGui.QApplication.translate("fmtomo_parameters", "Specifiy directory for FMTOMO simulation.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("fmtomo_parameters", "Simulation\n"
"Directory  [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.browse_simuldir.setText(QtGui.QApplication.translate("fmtomo_parameters", "Browse", None, QtGui.QApplication.UnicodeUTF8))

