# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'picking_parameters_layout.ui'
#
# Created: Thu Aug  4 13:55:47 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_picking_parameters(object):
    def setupUi(self, picking_parameters):
        picking_parameters.setObjectName("picking_parameters")
        picking_parameters.resize(422, 798)
        picking_parameters.setMinimumSize(QtCore.QSize(0, 700))
        self.verticalLayout_4 = QtGui.QVBoxLayout(picking_parameters)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ncores = QtGui.QSpinBox(picking_parameters)
        self.ncores.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ncores.setMinimum(1)
        self.ncores.setMaximum(10000)
        self.ncores.setObjectName("ncores")
        self.horizontalLayout.addWidget(self.ncores)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit_vmin = QtGui.QLineEdit(picking_parameters)
        self.lineEdit_vmin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_vmin.setObjectName("lineEdit_vmin")
        self.verticalLayout_2.addWidget(self.lineEdit_vmin)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_vmax = QtGui.QLineEdit(picking_parameters)
        self.lineEdit_vmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_vmax.setObjectName("lineEdit_vmax")
        self.verticalLayout.addWidget(self.lineEdit_vmax)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.slider_folm = QtGui.QSlider(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_folm.sizePolicy().hasHeightForWidth())
        self.slider_folm.setSizePolicy(sizePolicy)
        self.slider_folm.setMinimum(1)
        self.slider_folm.setMaximum(100)
        self.slider_folm.setProperty("value", 60)
        self.slider_folm.setOrientation(QtCore.Qt.Horizontal)
        self.slider_folm.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_folm.setTickInterval(10)
        self.slider_folm.setObjectName("slider_folm")
        self.horizontalLayout_2.addWidget(self.slider_folm)
        self.label_folm = QtGui.QLabel(picking_parameters)
        self.label_folm.setAlignment(QtCore.Qt.AlignCenter)
        self.label_folm.setObjectName("label_folm")
        self.horizontalLayout_2.addWidget(self.label_folm)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.checkBox_AIC = QtGui.QCheckBox(picking_parameters)
        self.checkBox_AIC.setText("")
        self.checkBox_AIC.setChecked(True)
        self.checkBox_AIC.setObjectName("checkBox_AIC")
        self.horizontalLayout_5.addWidget(self.checkBox_AIC)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtGui.QLabel(picking_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_aicleft = QtGui.QLineEdit(picking_parameters)
        self.lineEdit_aicleft.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_aicleft.setObjectName("lineEdit_aicleft")
        self.horizontalLayout_7.addWidget(self.lineEdit_aicleft)
        self.lineEdit_aicright = QtGui.QLineEdit(picking_parameters)
        self.lineEdit_aicright.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_aicright.setObjectName("lineEdit_aicright")
        self.horizontalLayout_7.addWidget(self.lineEdit_aicright)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_snr = QtGui.QVBoxLayout()
        self.verticalLayout_snr.setObjectName("verticalLayout_snr")
        self.line = QtGui.QFrame(picking_parameters)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_snr.addWidget(self.line)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtGui.QLabel(picking_parameters)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.radioButton_const = QtGui.QRadioButton(picking_parameters)
        self.radioButton_const.setChecked(True)
        self.radioButton_const.setObjectName("radioButton_const")
        self.horizontalLayout_9.addWidget(self.radioButton_const)
        self.radioButton_dyn = QtGui.QRadioButton(picking_parameters)
        self.radioButton_dyn.setObjectName("radioButton_dyn")
        self.horizontalLayout_9.addWidget(self.radioButton_dyn)
        self.verticalLayout_snr.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_13 = QtGui.QLabel(picking_parameters)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        self.doubleSpinBox_constSNR = QtGui.QDoubleSpinBox(picking_parameters)
        self.doubleSpinBox_constSNR.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBox_constSNR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_constSNR.setDecimals(1)
        self.doubleSpinBox_constSNR.setMinimum(1.0)
        self.doubleSpinBox_constSNR.setMaximum(10000.0)
        self.doubleSpinBox_constSNR.setSingleStep(0.1)
        self.doubleSpinBox_constSNR.setProperty("value", 8.0)
        self.doubleSpinBox_constSNR.setObjectName("doubleSpinBox_constSNR")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_constSNR)
        self.verticalLayout_snr.addLayout(self.horizontalLayout_10)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtGui.QLabel(picking_parameters)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(picking_parameters)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.p1 = QtGui.QDoubleSpinBox(picking_parameters)
        self.p1.setDecimals(6)
        self.p1.setMinimum(-100.0)
        self.p1.setMaximum(100.0)
        self.p1.setSingleStep(0.0001)
        self.p1.setProperty("value", 0.004)
        self.p1.setObjectName("p1")
        self.gridLayout_2.addWidget(self.p1, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(picking_parameters)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_12 = QtGui.QLabel(picking_parameters)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 2, 1, 1)
        self.p2 = QtGui.QDoubleSpinBox(picking_parameters)
        self.p2.setDecimals(6)
        self.p2.setMinimum(-100.0)
        self.p2.setMaximum(100.0)
        self.p2.setSingleStep(0.001)
        self.p2.setProperty("value", -0.0007)
        self.p2.setObjectName("p2")
        self.gridLayout_2.addWidget(self.p2, 2, 3, 1, 1)
        self.shift_dist = QtGui.QSpinBox(picking_parameters)
        self.shift_dist.setMinimum(-10000)
        self.shift_dist.setMaximum(10000)
        self.shift_dist.setProperty("value", 30)
        self.shift_dist.setObjectName("shift_dist")
        self.gridLayout_2.addWidget(self.shift_dist, 1, 1, 1, 1)
        self.shift_snr = QtGui.QSpinBox(picking_parameters)
        self.shift_snr.setMinimum(-10000)
        self.shift_snr.setMaximum(10000)
        self.shift_snr.setProperty("value", 100)
        self.shift_snr.setObjectName("shift_snr")
        self.gridLayout_2.addWidget(self.shift_snr, 1, 3, 1, 1)
        self.verticalLayout_snr.addLayout(self.gridLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_snr)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.vlayout_plot = QtGui.QVBoxLayout()
        self.vlayout_plot.setObjectName("vlayout_plot")
        self.verticalLayout_4.addLayout(self.vlayout_plot)
        self.buttonBox = QtGui.QDialogButtonBox(picking_parameters)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(picking_parameters)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), picking_parameters.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), picking_parameters.reject)
        QtCore.QMetaObject.connectSlotsByName(picking_parameters)

    def retranslateUi(self, picking_parameters):
        picking_parameters.setWindowTitle(QtGui.QApplication.translate("picking_parameters", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("picking_parameters", "Choose parameters for FMTOMO simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setToolTip(QtGui.QApplication.translate("picking_parameters", "Amount of CPU kernels used.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("picking_parameters", "nproc [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setToolTip(QtGui.QApplication.translate("picking_parameters", "Minimum permitted direct velocity (apparent velocity!).", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("picking_parameters", "vmin [m/s] [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_vmin.setText(QtGui.QApplication.translate("picking_parameters", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setToolTip(QtGui.QApplication.translate("picking_parameters", "Maximum permitted direct velocity (apparent velocity!).", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("picking_parameters", "vmax [m/s] [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_vmax.setText(QtGui.QApplication.translate("picking_parameters", "5000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setToolTip(QtGui.QApplication.translate("picking_parameters", "Value between 1 and 100 % for threshold picking algorithm (Default = 60%).", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("picking_parameters", "Fraction of local maximum [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_folm.setText(QtGui.QApplication.translate("picking_parameters", "60 %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setToolTip(QtGui.QApplication.translate("picking_parameters", "Use additional Akaike Information Criterion for picking.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("picking_parameters", "AIC [?]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setToolTip(QtGui.QApplication.translate("picking_parameters", "Samples before and after initial HOS pick.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("picking_parameters", "AIC window samples\n"
"(only if AIC checked)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_aicleft.setText(QtGui.QApplication.translate("picking_parameters", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_aicright.setText(QtGui.QApplication.translate("picking_parameters", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("picking_parameters", "SNR threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_const.setText(QtGui.QApplication.translate("picking_parameters", "constant", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_dyn.setText(QtGui.QApplication.translate("picking_parameters", "dynamic (advanced)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("picking_parameters", "Constant SNR threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("picking_parameters", "Shift distance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("picking_parameters", "p1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("picking_parameters", "Shift SNR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("picking_parameters", "p2", None, QtGui.QApplication.UnicodeUTF8))

