# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'postprocessing_layout.ui'
#
# Created: Tue Aug  9 10:36:58 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_postprocessing(object):
    def setupUi(self, postprocessing):
        postprocessing.setObjectName("postprocessing")
        postprocessing.resize(640, 479)
        self.verticalLayout_2 = QtGui.QVBoxLayout(postprocessing)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_rect = QtGui.QPushButton(postprocessing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_rect.sizePolicy().hasHeightForWidth())
        self.pushButton_rect.setSizePolicy(sizePolicy)
        self.pushButton_rect.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_rect.setObjectName("pushButton_rect")
        self.horizontalLayout.addWidget(self.pushButton_rect)
        self.pushButton_poly = QtGui.QPushButton(postprocessing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_poly.sizePolicy().hasHeightForWidth())
        self.pushButton_poly.setSizePolicy(sizePolicy)
        self.pushButton_poly.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_poly.setObjectName("pushButton_poly")
        self.horizontalLayout.addWidget(self.pushButton_poly)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.label = QtGui.QLabel(postprocessing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(postprocessing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_snr = QtGui.QPushButton(postprocessing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_snr.sizePolicy().hasHeightForWidth())
        self.pushButton_snr.setSizePolicy(sizePolicy)
        self.pushButton_snr.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_snr.setObjectName("pushButton_snr")
        self.horizontalLayout_3.addWidget(self.pushButton_snr)
        self.pushButton_pe = QtGui.QPushButton(postprocessing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_pe.sizePolicy().hasHeightForWidth())
        self.pushButton_pe.setSizePolicy(sizePolicy)
        self.pushButton_pe.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_pe.setObjectName("pushButton_pe")
        self.horizontalLayout_3.addWidget(self.pushButton_pe)
        self.pushButton_spe = QtGui.QPushButton(postprocessing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_spe.sizePolicy().hasHeightForWidth())
        self.pushButton_spe.setSizePolicy(sizePolicy)
        self.pushButton_spe.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_spe.setObjectName("pushButton_spe")
        self.horizontalLayout_3.addWidget(self.pushButton_spe)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_plot = QtGui.QHBoxLayout()
        self.horizontalLayout_plot.setObjectName("horizontalLayout_plot")
        self.verticalLayout.addLayout(self.horizontalLayout_plot)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtGui.QDialogButtonBox(postprocessing)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(postprocessing)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), postprocessing.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), postprocessing.reject)
        QtCore.QMetaObject.connectSlotsByName(postprocessing)

    def retranslateUi(self, postprocessing):
        postprocessing.setWindowTitle(QtGui.QApplication.translate("postprocessing", "Postprocessing", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_rect.setText(QtGui.QApplication.translate("postprocessing", "Rectangle", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_poly.setText(QtGui.QApplication.translate("postprocessing", "Polygon", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("postprocessing", "Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("postprocessing", "Color by", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_snr.setText(QtGui.QApplication.translate("postprocessing", "SNR", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pe.setText(QtGui.QApplication.translate("postprocessing", "PE", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_spe.setText(QtGui.QApplication.translate("postprocessing", "SPE", None, QtGui.QApplication.UnicodeUTF8))

