from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("ActiveSeismoPick3D")
        MainWindow.resize(252, 350)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(252, 350))
        MainWindow.setMaximumSize(QtCore.QSize(252, 350))
        MainWindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.postprocessing = QtGui.QPushButton(self.centralwidget)
        self.postprocessing.setGeometry(QtCore.QRect(0, 220, 251, 27))
        self.postprocessing.setObjectName("postprocessing")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 231, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.verticalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.survey_active = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.survey_active.setEnabled(True)
        self.survey_active.setMouseTracking(False)
        self.survey_active.setStatusTip("")
        self.survey_active.setWhatsThis("")
        self.survey_active.setAccessibleName("")
        self.survey_active.setAccessibleDescription("")
        self.survey_active.setCheckable(False)
        self.survey_active.setObjectName("survey_active")
        self.horizontalLayout.addWidget(self.survey_active)
        self.picked_active = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.picked_active.setEnabled(True)
        self.picked_active.setMouseTracking(False)
        self.picked_active.setStatusTip("")
        self.picked_active.setWhatsThis("")
        self.picked_active.setAccessibleName("")
        self.picked_active.setAccessibleDescription("")
        self.picked_active.setCheckable(False)
        self.picked_active.setObjectName("picked_active")
        self.horizontalLayout.addWidget(self.picked_active)
        self.gen_new_survey = QtGui.QPushButton(self.centralwidget)
        self.gen_new_survey.setGeometry(QtCore.QRect(1, 47, 251, 27))
        self.gen_new_survey.setObjectName("gen_new_survey")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(1, 160, 249, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.load_survey = QtGui.QPushButton(self.centralwidget)
        self.load_survey.setGeometry(QtCore.QRect(1, 86, 251, 27))
        self.load_survey.setObjectName("load_survey")
        self.save_survey = QtGui.QPushButton(self.centralwidget)
        self.save_survey.setGeometry(QtCore.QRect(1, 125, 251, 27))
        self.save_survey.setObjectName("save_survey")
        self.picker = QtGui.QPushButton(self.centralwidget)
        self.picker.setGeometry(QtCore.QRect(1, 179, 251, 27))
        self.picker.setObjectName("picker")
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(1, 250, 249, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.fmtomo = QtGui.QPushButton(self.centralwidget)
        self.fmtomo.setGeometry(QtCore.QRect(1, 270, 251, 27))
        self.fmtomo.setObjectName("fmtomo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 252, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.postprocessing.setText(QtGui.QApplication.translate("MainWindow", "Postprocessing", None, QtGui.QApplication.UnicodeUTF8))
        self.survey_active.setText(QtGui.QApplication.translate("MainWindow", "Survey active", None, QtGui.QApplication.UnicodeUTF8))
        self.picked_active.setText(QtGui.QApplication.translate("MainWindow", "picked", None, QtGui.QApplication.UnicodeUTF8))
        self.gen_new_survey.setText(QtGui.QApplication.translate("MainWindow", "Generate new Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.load_survey.setText(QtGui.QApplication.translate("MainWindow", "Load Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.save_survey.setText(QtGui.QApplication.translate("MainWindow", "Save Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.picker.setText(QtGui.QApplication.translate("MainWindow", "Autopicker", None, QtGui.QApplication.UnicodeUTF8))
        self.fmtomo.setText(QtGui.QApplication.translate("MainWindow", "FMTOMO Simulation", None, QtGui.QApplication.UnicodeUTF8))

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(380, 160)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_rec = QtGui.QLineEdit(Dialog)
        self.lineEdit_rec.setObjectName("lineEdit_rec")
        self.gridLayout.addWidget(self.lineEdit_rec, 0, 1, 1, 1)
        self.pushButton_rec = QtGui.QPushButton(Dialog)
        self.pushButton_rec.setObjectName("pushButton_rec")
        self.gridLayout.addWidget(self.pushButton_rec, 0, 2, 1, 1)
        self.label_rec = QtGui.QLabel(Dialog)
        self.label_rec.setObjectName("label_rec")
        self.gridLayout.addWidget(self.label_rec, 0, 0, 1, 1)
        self.lineEdit_obs = QtGui.QLineEdit(Dialog)
        self.lineEdit_obs.setObjectName("lineEdit_obs")
        self.gridLayout.addWidget(self.lineEdit_obs, 2, 1, 1, 1)
        self.label_obs = QtGui.QLabel(Dialog)
        self.label_obs.setObjectName("label_obs")
        self.gridLayout.addWidget(self.label_obs, 2, 0, 1, 1)
        self.pushButton_obs = QtGui.QPushButton(Dialog)
        self.pushButton_obs.setObjectName("pushButton_obs")
        self.gridLayout.addWidget(self.pushButton_obs, 2, 2, 1, 1)
        self.label_src = QtGui.QLabel(Dialog)
        self.label_src.setObjectName("label_src")
        self.gridLayout.addWidget(self.label_src, 1, 0, 1, 1)
        self.lineEdit_src = QtGui.QLineEdit(Dialog)
        self.lineEdit_src.setObjectName("lineEdit_src")
        self.gridLayout.addWidget(self.lineEdit_src, 1, 1, 1, 1)
        self.pushButton_src = QtGui.QPushButton(Dialog)
        self.pushButton_src.setObjectName("pushButton_src")
        self.gridLayout.addWidget(self.pushButton_src, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_rec.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_rec.setText(QtGui.QApplication.translate("Dialog", "Receiver\n"
"File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_obs.setText(QtGui.QApplication.translate("Dialog", "Seismogram\n"
"Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_obs.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_src.setText(QtGui.QApplication.translate("Dialog", "Source\n"
"File", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_src.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))

class Ui_Picking_parameters(object):
    def setupUi(self, Picking_parameters):
        Picking_parameters.setObjectName("Picking_parameters")
        Picking_parameters.resize(300, 300)
        self.gridLayoutWidget = QtGui.QWidget(Picking_parameters)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 250, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_cores = QtGui.QLabel(self.gridLayoutWidget)
        self.label_cores.setObjectName("label_cores")
        self.gridLayout.addWidget(self.label_cores, 0, 0, 1, 1)
        self.label_vmax = QtGui.QLabel(self.gridLayoutWidget)
        self.label_vmax.setObjectName("label_vmax")
        self.gridLayout.addWidget(self.label_vmax, 2, 0, 1, 1)
        self.label_vmin = QtGui.QLabel(self.gridLayoutWidget)
        self.label_vmin.setObjectName("label_vmin")
        self.gridLayout.addWidget(self.label_vmin, 1, 0, 1, 1)
        self.lineEdit_ncores = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ncores.setObjectName("lineEdit_ncores")
        self.gridLayout.addWidget(self.lineEdit_ncores, 0, 1, 1, 1)
        self.lineEdit_vmin = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_vmin.setObjectName("lineEdit_vmin")
        self.gridLayout.addWidget(self.lineEdit_vmin, 1, 1, 1, 1)
        self.lineEdit_vmax = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_vmax.setObjectName("lineEdit_vmax")
        self.gridLayout.addWidget(self.lineEdit_vmax, 2, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 4, 1, 1, 1)
        self.label_folm = QtGui.QLabel(self.gridLayoutWidget)
        self.label_folm.setObjectName("label_folm")
        self.gridLayout.addWidget(self.label_folm, 3, 0, 1, 1)
        self.label_aic = QtGui.QLabel(self.gridLayoutWidget)
        self.label_aic.setObjectName("label_aic")
        self.gridLayout.addWidget(self.label_aic, 4, 0, 1, 1)
        self.lineEdit_folm = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_folm.setObjectName("lineEdit_folm")
        self.gridLayout.addWidget(self.lineEdit_folm, 3, 1, 1, 1)
        self.label_aicwindow = QtGui.QLabel(self.gridLayoutWidget)
        self.label_aicwindow.setObjectName("label_aicwindow")
        self.gridLayout.addWidget(self.label_aicwindow, 5, 0, 1, 1)
        self.lineEdit_aicwindow = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_aicwindow.setObjectName("lineEdit_aicwindow")
        self.gridLayout.addWidget(self.lineEdit_aicwindow, 5, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Picking_parameters)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.setGeometry(QtCore.QRect(10, 240, 250, 32))

        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Picking_parameters.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Picking_parameters.reject)
        self.retranslateUi(Picking_parameters)
        QtCore.QMetaObject.connectSlotsByName(Picking_parameters)

    def retranslateUi(self, Picking_parameters):
        Picking_parameters.setWindowTitle(QtGui.QApplication.translate("Picking_parameters", "Picking_parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cores.setText(QtGui.QApplication.translate("Picking_parameters", "Number of cores", None, QtGui.QApplication.UnicodeUTF8))
        self.label_vmax.setText(QtGui.QApplication.translate("Picking_parameters", "Vmax (default = 5000m/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_vmin.setText(QtGui.QApplication.translate("Picking_parameters", "Vmin (default = 333 m/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ncores.setText(QtGui.QApplication.translate("Picking_parameters", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_vmin.setText(QtGui.QApplication.translate("Picking_parameters", "333", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_vmax.setText(QtGui.QApplication.translate("Picking_parameters", "5000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_folm.setText(QtGui.QApplication.translate("Picking_parameters", "Fraction of local maximum\n"
"(default = 0.6)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_aic.setText(QtGui.QApplication.translate("Picking_parameters", "AIC", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_folm.setText(QtGui.QApplication.translate("Picking_parameters", "0.6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_aicwindow.setText(QtGui.QApplication.translate("Picking_parameters", "AIC window (only if AIC\n"
" is checked)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_aicwindow.setText(QtGui.QApplication.translate("Picking_parameters", "15, 0", None, QtGui.QApplication.UnicodeUTF8))

class Ui_fmtomo_parameters(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 520)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(320, 520))
        Dialog.setMaximumSize(QtCore.QSize(320, 520))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 480, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtGui.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 240, 281, 79))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.pgrid_x = QtGui.QLineEdit(self.gridLayoutWidget)
        self.pgrid_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pgrid_x.setObjectName("pgrid_x")
        self.gridLayout.addWidget(self.pgrid_x, 1, 1, 1, 1)
        self.pgrid_y = QtGui.QLineEdit(self.gridLayoutWidget)
        self.pgrid_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pgrid_y.setObjectName("pgrid_y")
        self.gridLayout.addWidget(self.pgrid_y, 1, 2, 1, 1)
        self.pgrid_z = QtGui.QLineEdit(self.gridLayoutWidget)
        self.pgrid_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pgrid_z.setObjectName("pgrid_z")
        self.gridLayout.addWidget(self.pgrid_z, 1, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.invgrid_x = QtGui.QLineEdit(self.gridLayoutWidget)
        self.invgrid_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.invgrid_x.setObjectName("invgrid_x")
        self.gridLayout.addWidget(self.invgrid_x, 2, 1, 1, 1)
        self.invgrid_y = QtGui.QLineEdit(self.gridLayoutWidget)
        self.invgrid_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.invgrid_y.setObjectName("invgrid_y")
        self.gridLayout.addWidget(self.invgrid_y, 2, 2, 1, 1)
        self.invgrid_z = QtGui.QLineEdit(self.gridLayoutWidget)
        self.invgrid_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.invgrid_z.setObjectName("invgrid_z")
        self.gridLayout.addWidget(self.invgrid_z, 2, 3, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 160, 201, 61))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.bbot = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.bbot.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bbot.setObjectName("bbot")
        self.gridLayout_2.addWidget(self.bbot, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.btop = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.btop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.btop.setObjectName("btop")
        self.gridLayout_2.addWidget(self.btop, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 2, 1, 1)
        self.gridLayoutWidget_3 = QtGui.QWidget(Dialog)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 60, 201, 31))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.nIter = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.nIter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nIter.setProperty("value", 1)
        self.nIter.setObjectName("nIter")
        self.gridLayout_3.addWidget(self.nIter, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 340, 161, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.cushion = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.cushion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cushion.setObjectName("cushion")
        self.horizontalLayout.addWidget(self.cushion)
        self.label_12 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 291, 32))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_17 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.fmtomo_dir = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.fmtomo_dir.setObjectName("fmtomo_dir")
        self.horizontalLayout_4.addWidget(self.fmtomo_dir)
        self.browse_tomodir = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.browse_tomodir.setObjectName("browse_tomodir")
        self.horizontalLayout_4.addWidget(self.browse_tomodir)
        self.line = QtGui.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(7, 220, 301, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(10, 320, 301, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayoutWidget_4 = QtGui.QWidget(Dialog)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 390, 291, 80))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.customgrid = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.customgrid.setObjectName("customgrid")
        self.gridLayout_4.addWidget(self.customgrid, 0, 1, 1, 1)
        self.browse_customgrid = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.browse_customgrid.setObjectName("browse_customgrid")
        self.gridLayout_4.addWidget(self.browse_customgrid, 0, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 1, 0, 1, 1)
        self.simuldir = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.simuldir.setObjectName("simuldir")
        self.gridLayout_4.addWidget(self.simuldir, 1, 1, 1, 1)
        self.browse_simuldir = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.browse_simuldir.setObjectName("browse_simuldir")
        self.gridLayout_4.addWidget(self.browse_simuldir, 1, 2, 1, 1)
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(10, 370, 301, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtGui.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(10, 90, 301, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtGui.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(10, 40, 301, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(220, 60, 81, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.nproc = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.nproc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nproc.setObjectName("nproc")
        self.horizontalLayout_2.addWidget(self.nproc)
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(10, 102, 271, 16))
        self.label_18.setObjectName("label_18")
        self.horizontalLayoutWidget_5 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 120, 291, 32))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_19 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_5.addWidget(self.label_19)
        self.seisarray = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.seisarray.setObjectName("seisarray")
        self.horizontalLayout_5.addWidget(self.seisarray)
        self.browse_seisarray = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.browse_seisarray.setObjectName("browse_seisarray")
        self.horizontalLayout_5.addWidget(self.browse_seisarray)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Number of Ponts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Propagation Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.pgrid_x.setText(QtGui.QApplication.translate("Dialog", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.pgrid_y.setText(QtGui.QApplication.translate("Dialog", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.pgrid_z.setText(QtGui.QApplication.translate("Dialog", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Inversion Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.invgrid_x.setText(QtGui.QApplication.translate("Dialog", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.invgrid_y.setText(QtGui.QApplication.translate("Dialog", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.invgrid_z.setText(QtGui.QApplication.translate("Dialog", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Bottom boundary", None, QtGui.QApplication.UnicodeUTF8))
        self.bbot.setText(QtGui.QApplication.translate("Dialog", "-50", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Top boundary", None, QtGui.QApplication.UnicodeUTF8))
        self.btop.setText(QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Cushion factor", None, QtGui.QApplication.UnicodeUTF8))
        self.cushion.setText(QtGui.QApplication.translate("Dialog", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "FMTOMO\n"
"installation", None, QtGui.QApplication.UnicodeUTF8))
        self.browse_tomodir.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Custom velocity\n"
"grid (earthmodel)", None, QtGui.QApplication.UnicodeUTF8))
        self.browse_customgrid.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Simulation\n"
"Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.browse_simuldir.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "nproc", None, QtGui.QApplication.UnicodeUTF8))
        self.nproc.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Grid definitions from seismic Array:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Seismic\n"
"Array", None, QtGui.QApplication.UnicodeUTF8))
        self.browse_seisarray.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
