# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'asp3d_layout.ui'
#
# Created: Wed Jun 15 11:55:58 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(252, 350)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(252, 350))
        MainWindow.setMaximumSize(QtCore.QSize(252, 350))
        MainWindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../asp3d_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.postprocessing = QtGui.QPushButton(self.centralwidget)
        self.postprocessing.setGeometry(QtCore.QRect(0, 220, 251, 27))
        self.postprocessing.setObjectName("postprocessing")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 251, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.verticalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.survey_active = QtGui.QLabel(self.verticalLayoutWidget)
        self.survey_active.setMaximumSize(QtCore.QSize(20, 20))
        self.survey_active.setMidLineWidth(0)
        self.survey_active.setText("")
        self.survey_active.setObjectName("survey_active")
        self.horizontalLayout.addWidget(self.survey_active)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.picked_active = QtGui.QLabel(self.verticalLayoutWidget)
        self.picked_active.setMaximumSize(QtCore.QSize(20, 20))
        self.picked_active.setMidLineWidth(0)
        self.picked_active.setText("")
        self.picked_active.setObjectName("picked_active")
        self.horizontalLayout.addWidget(self.picked_active)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.gen_new_survey = QtGui.QPushButton(self.centralwidget)
        self.gen_new_survey.setGeometry(QtCore.QRect(1, 47, 251, 27))
        self.gen_new_survey.setObjectName("gen_new_survey")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(1, 160, 249, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.load_survey = QtGui.QPushButton(self.centralwidget)
        self.load_survey.setGeometry(QtCore.QRect(1, 86, 251, 27))
        self.load_survey.setObjectName("load_survey")
        self.save_survey = QtGui.QPushButton(self.centralwidget)
        self.save_survey.setGeometry(QtCore.QRect(1, 125, 251, 27))
        self.save_survey.setObjectName("save_survey")
        self.picker = QtGui.QPushButton(self.centralwidget)
        self.picker.setGeometry(QtCore.QRect(1, 179, 251, 27))
        self.picker.setObjectName("picker")
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(1, 250, 249, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.fmtomo = QtGui.QPushButton(self.centralwidget)
        self.fmtomo.setGeometry(QtCore.QRect(1, 270, 251, 27))
        self.fmtomo.setObjectName("fmtomo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 252, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ActiveSeismoPick 3D", None, QtGui.QApplication.UnicodeUTF8))
        self.postprocessing.setText(QtGui.QApplication.translate("MainWindow", "Postprocessing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Survey active", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Survey picked", None, QtGui.QApplication.UnicodeUTF8))
        self.gen_new_survey.setText(QtGui.QApplication.translate("MainWindow", "Generate new Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.load_survey.setText(QtGui.QApplication.translate("MainWindow", "Load Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.save_survey.setText(QtGui.QApplication.translate("MainWindow", "Save Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.picker.setText(QtGui.QApplication.translate("MainWindow", "Autopicker", None, QtGui.QApplication.UnicodeUTF8))
        self.fmtomo.setText(QtGui.QApplication.translate("MainWindow", "FMTOMO Simulation", None, QtGui.QApplication.UnicodeUTF8))

