class Ui_Picking_parameters(object):
    def setupUi(self, Picking_parameters):
        Picking_parameters.setObjectName("Picking_parameters")
        Picking_parameters.resize(300, 300)
        self.gridLayoutWidget = QtGui.QWidget(Picking_parameters)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 250, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_cores = QtGui.QLabel(self.gridLayoutWidget)
        self.label_cores.setObjectName("label_cores")
        self.gridLayout.addWidget(self.label_cores, 0, 0, 1, 1)
        self.label_vmax = QtGui.QLabel(self.gridLayoutWidget)
        self.label_vmax.setObjectName("label_vmax")
        self.gridLayout.addWidget(self.label_vmax, 2, 0, 1, 1)
        self.label_vmin = QtGui.QLabel(self.gridLayoutWidget)
        self.label_vmin.setObjectName("label_vmin")
        self.gridLayout.addWidget(self.label_vmin, 1, 0, 1, 1)
        self.lineEdit_ncores = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ncores.setObjectName("lineEdit_ncores")
        self.gridLayout.addWidget(self.lineEdit_ncores, 0, 1, 1, 1)
        self.lineEdit_vmin = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_vmin.setObjectName("lineEdit_vmin")
        self.gridLayout.addWidget(self.lineEdit_vmin, 1, 1, 1, 1)
        self.lineEdit_vmax = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_vmax.setObjectName("lineEdit_vmax")
        self.gridLayout.addWidget(self.lineEdit_vmax, 2, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 4, 1, 1, 1)
        self.label_folm = QtGui.QLabel(self.gridLayoutWidget)
        self.label_folm.setObjectName("label_folm")
        self.gridLayout.addWidget(self.label_folm, 3, 0, 1, 1)
        self.label_aic = QtGui.QLabel(self.gridLayoutWidget)
        self.label_aic.setObjectName("label_aic")
        self.gridLayout.addWidget(self.label_aic, 4, 0, 1, 1)
        self.lineEdit_folm = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_folm.setObjectName("lineEdit_folm")
        self.gridLayout.addWidget(self.lineEdit_folm, 3, 1, 1, 1)
        self.label_aicwindow = QtGui.QLabel(self.gridLayoutWidget)
        self.label_aicwindow.setObjectName("label_aicwindow")
        self.gridLayout.addWidget(self.label_aicwindow, 5, 0, 1, 1)
        self.lineEdit_aicwindow = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_aicwindow.setObjectName("lineEdit_aicwindow")
        self.gridLayout.addWidget(self.lineEdit_aicwindow, 5, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Picking_parameters)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.setGeometry(QtCore.QRect(10, 240, 250, 32))

        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Picking_parameters.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Picking_parameters.reject)
        self.retranslateUi(Picking_parameters)
        QtCore.QMetaObject.connectSlotsByName(Picking_parameters)

    def retranslateUi(self, Picking_parameters):
        Picking_parameters.setWindowTitle(QtGui.QApplication.translate("Picking_parameters", "Picking_parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cores.setText(QtGui.QApplication.translate("Picking_parameters", "Number of cores", None, QtGui.QApplication.UnicodeUTF8))
        self.label_vmax.setText(QtGui.QApplication.translate("Picking_parameters", "Vmax (default = 5000m/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_vmin.setText(QtGui.QApplication.translate("Picking_parameters", "Vmin (default = 333 m/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ncores.setText(QtGui.QApplication.translate("Picking_parameters", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_vmin.setText(QtGui.QApplication.translate("Picking_parameters", "333", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_vmax.setText(QtGui.QApplication.translate("Picking_parameters", "5000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_folm.setText(QtGui.QApplication.translate("Picking_parameters", "Fraction of local maximum\n"
"(default = 0.6)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_aic.setText(QtGui.QApplication.translate("Picking_parameters", "AIC", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_folm.setText(QtGui.QApplication.translate("Picking_parameters", "0.6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_aicwindow.setText(QtGui.QApplication.translate("Picking_parameters", "AIC window (only if AIC\n"
" is checked)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_aicwindow.setText(QtGui.QApplication.translate("Picking_parameters", "15, 0", None, QtGui.QApplication.UnicodeUTF8))
